language: java

dist: trusty

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d
  - docker ps -a

before_script:
  - cd ../../microserviceBdd

script:
  - mvn test
  - cd ../docker/dev
  - docker-compose stop
  - docker-compose rm -f
  - docker-compose up -d
  - docker ps -a
  - cd ../../microserviceBdd


after_success:
  - mvn --file pom.xml cobertura:cobertura -P test
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
