version: '2.1'
services:
  bdd-badj:
    image: mysql:8.0.18
    restart: always
    environment:
      LANG: C.UTF-8
      TZ: Europe/Paris
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'nicotine'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - '127.0.0.1:9032:3306'
    expose:
      - '3306'
    volumes:
      - "./dev/init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - network-badj


  microservicebdd:
    depends_on:
      bdd-badj:
        condition: service_healthy
    build:
      context: ../microserviceBdd
      dockerfile: Dockerfile
    container_name: microservice-web-1.0.2
    ports:
      - 9001:9001
    environment:
      token-secret: Badj
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nicotine
      SPRING_DATASOURCE_URL: jdbc:mysql://bdd-badj/badj?serverTimezone=UTC
    networks:
      - network-badj


  applicationwebangular:
    depends_on:
      - bdd-badj
      - microservicebdd
    build:
      context: ../applicationWebAngular
      dockerfile: Dockerfile
    container_name: applicationwebangular
    volumes:
      - './applicationwebangular:/usr/src/app'
    ports:
      - '4200:4200'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    networks:
      - network-badj


networks:
  network-badj:
    driver: bridge

volumes:
  front:
