version: '2'
services:
  badj:
    image: mysql:8.0.18
    restart: always
    environment:
      LANG: C.UTF-8
      TZ: Europe/Paris

#      MYSQL_DATABASE: 'badj'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'nicotine'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '127.0.0.1:9032:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - "./dev/init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"








